#!/bin/bash
# gpu-summon Full-Stack onstart
#
# Runs inside the privileged vast.ai container. Brings up four things in order:
#   1) dockerd (so xaresaicoder's docker-compose stack can use Docker)
#   2) llama-server as a host process (uses GPU directly, not in a sub-container)
#   3) xaresaicoder via its deploy.sh
#   4) Caddy as the public-facing reverse proxy with TLS+BasicAuth
#
# Required env (injected by summon.py):
#   DOMAIN              e.g. mybox.duckdns.org
#   DUCKDNS_TOKEN       duckdns API token (for ACME DNS-01)
#   LLAMA_API_KEY       Bearer token for llama-server
#   XARES_BASIC_USER    HTTP-Basic username for xares frontend
#   XARES_BASIC_HASH    bcrypt hash of the BasicAuth password (generated by summon.py)
# Optional:
#   LLAMA_MODEL         default: unsloth/Qwen3.6-27B-GGUF:UD-Q5_K_XL
#   LLAMA_CTX           default: 65536
#   LLAMA_PARALLEL      default: 4
#   ACME_EMAIL          default: admin@${DOMAIN}

set -euo pipefail

LLAMA_MODEL="${LLAMA_MODEL:-unsloth/Qwen3.6-27B-GGUF:UD-Q5_K_XL}"
LLAMA_CTX="${LLAMA_CTX:-65536}"
LLAMA_PARALLEL="${LLAMA_PARALLEL:-4}"
ACME_EMAIL="${ACME_EMAIL:-admin@${DOMAIN}}"

log() { echo "[onstart $(date -u +%H:%M:%S)] $*"; }

require() {
    local name="$1"
    if [[ -z "${!name:-}" ]]; then
        log "FATAL: required env var $name is empty"
        exit 1
    fi
}

require DOMAIN
require DUCKDNS_TOKEN
require LLAMA_API_KEY
require XARES_BASIC_USER
require XARES_BASIC_HASH

mkdir -p /var/log /etc/caddy /workspace/hf_cache

# 1) dockerd. vfs storage-driver is slow but works without overlay2 kernel
#    features that some vast hosts lack. Logs to /var/log/dockerd.log so
#    failures are diagnosable post-mortem via SSH.
log "starting dockerd (DinD, vfs storage)"
dockerd --host=unix:///var/run/docker.sock --storage-driver=vfs \
        > /var/log/dockerd.log 2>&1 &
DOCKERD_PID=$!

log "waiting for dockerd socket..."
for i in $(seq 1 60); do
    if docker info >/dev/null 2>&1; then
        log "dockerd ready after ${i}s"
        break
    fi
    if ! kill -0 "$DOCKERD_PID" 2>/dev/null; then
        log "FATAL: dockerd died, last log lines:"
        tail -50 /var/log/dockerd.log || true
        exit 2
    fi
    sleep 1
done
docker info >/dev/null 2>&1 || { log "FATAL: dockerd not responsive after 60s"; exit 2; }

# 2) llama-server. Same flags the existing self-contained backend uses
#    (see summon.py BACKENDS["llamacpp"]["onstart_template"]), just rendered
#    here as a host process. --host 127.0.0.1 because Caddy fronts it.
log "starting llama-server in background (model=$LLAMA_MODEL ctx=$LLAMA_CTX parallel=$LLAMA_PARALLEL)"
HF_HOME=/workspace/hf_cache LD_LIBRARY_PATH=/app setsid nohup /app/llama-server \
    -hf "$LLAMA_MODEL" \
    --host 127.0.0.1 --port 8080 \
    --n-gpu-layers 999 \
    --ctx-size "$LLAMA_CTX" \
    --parallel "$LLAMA_PARALLEL" \
    --cache-type-k q8_0 --cache-type-v q8_0 \
    --flash-attn on --jinja \
    --chat-template-kwargs '{"preserve_thinking":true}' \
    --temp 0.7 --top-p 0.8 --top-k 20 \
    --presence-penalty 1.5 --min-p 0.0 \
    --api-key "$LLAMA_API_KEY" \
    --metrics \
    > /var/log/llama-server.log 2>&1 < /dev/null &
disown || true

# 3) xaresaicoder. We use --use-registry so we pull pre-built images instead
#    of building locally (much faster, less RAM during boot). --skip-build
#    skips the code-server image rebuild for the same reason.
log "cloning xaresaicoder"
if [[ ! -d /opt/xares/.git ]]; then
    git clone --depth 1 https://github.com/dg1001/xaresaicoder /opt/xares
fi

log "rendering xares .env from template"
DOMAIN="$DOMAIN" envsubst < /opt/xares-env.template > /opt/xares/.env
cat /opt/xares/.env | sed 's/^/  [env] /'

log "deploying xaresaicoder stack"
cd /opt/xares
# yes pipe into deploy.sh in case it asks any interactive questions
yes "" | ./deploy.sh --skip-build --use-registry --skip-network 2>&1 | tee /var/log/xares-deploy.log

# 4) Caddy. Once xares is up on host port 80, Caddy fronts it on 443 with
#    a Let's Encrypt wildcard cert obtained via DNS-01 against duckdns.
log "rendering Caddyfile"
DOMAIN="$DOMAIN" \
DUCKDNS_TOKEN="$DUCKDNS_TOKEN" \
ACME_EMAIL="$ACME_EMAIL" \
XARES_BASIC_USER="$XARES_BASIC_USER" \
XARES_BASIC_HASH="$XARES_BASIC_HASH" \
    envsubst '${DOMAIN} ${DUCKDNS_TOKEN} ${ACME_EMAIL} ${XARES_BASIC_USER} ${XARES_BASIC_HASH}' \
    < /opt/Caddyfile.template > /etc/caddy/Caddyfile

log "starting caddy"
caddy run --config /etc/caddy/Caddyfile --adapter caddyfile \
    > /var/log/caddy.log 2>&1 &
disown || true

log "all services launched. tailing logs (use SSH + tail to watch individually)"
log "  - /var/log/dockerd.log"
log "  - /var/log/llama-server.log"
log "  - /var/log/xares-deploy.log"
log "  - /var/log/caddy.log"

# Block forever. Without this, the container exits as soon as we return.
sleep infinity
